# 📘 Clase 2: Operaciones vectorizadas y matriciales
## 🎯 Objetivos

- Realizar operaciones aritméticas sin usar bucles.

- Aplicar operaciones entre matrices y escalares.

- Calcular productos punto y transpuestas.

💻 Ejemplo

In [6]:
import numpy as np

a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

# Operaciones vectorizadas
print(f'Suma a + b = {a + b}')
print(f'\nMultiplicacion a * b = {a * b}')
print(f'\nPotencia de a ** 2 = {a ** 2}')
print(f'\nSumando por un valor a + 10 = {a + 10}')

# Producto punto y transpuesta
matriz = np.array([[1, 2], [3, 4]])
print(f'\nMatriz\n{matriz}')

print("\nTranspuesta:\n", matriz.T)
print("\nProducto punto:", np.dot(a, b))


Suma a + b = [5 7 9]

Multiplicacion a * b = [ 4 10 18]

Potencia de a ** 2 = [1 4 9]

Sumando por un valor a + 10 = [11 12 13]

Matriz
[[1 2]
 [3 4]]

Transpuesta:
 [[1 3]
 [2 4]]

Producto punto: 32


## 🧩 Ejercicios

1. Dadas a = [2, 4, 6] y b = [1, 3, 5], calcula:

- a + b, a - b, a * b

2. Crea una matriz 2x3 y calcula su transpuesta.

3. Realiza el producto punto entre a y b.

4. ¿Qué pasa si multiplicas una matriz 2x3 por una 3x2?

In [4]:
import numpy as np
# Respuesta 
#1. Dadas a = [2, 4, 6] y b = [1, 3, 5], calcula: 
# a + b, a - b, a * b 

a = [2, 4, 6]
b = [1, 3, 5]

a_arrays = np.array(a) # Creo la matriz a
b_arrays = np.array(b) # Creo la matriz b

suma = a_arrays + b_arrays
restas = a_arrays - b_arrays
multiplicacion = a_arrays * b_arrays

print(f'Suma a + b = {a_arrays + b_arrays}')
print(f'\nResta a - b = {a_arrays - b_arrays}')
print(f'\nMultiplicacion  a * b = {a_arrays * b_arrays} ')

Suma a + b = [ 3  7 11]

Resta a - b = [1 1 1]

Multiplicacion  a * b = [ 2 12 30] 


In [10]:
import numpy as pd 
# Respuesta
# Crea una matriz 2x3 y calcula su transpuesta.

matriz2X3 = np.array([[0,1,2],[3,4,5]])
print(f'Matriz Original:\n {matriz2X3}')

print(f'\nMatriz Transpuesta:\n {matriz2X3.T}')

Matriz Original:
 [[0 1 2]
 [3 4 5]]

Matriz Transpuesta:
 [[0 3]
 [1 4]
 [2 5]]


In [ ]:
import numpy as pd
# respuesta 
# 3. Realiza el producto punto entre a y b

a = [2, 4, 6]
b = [1, 3, 5]

a_arrays = np.array(a) # Creo la matriz a
b_arrays = np.array(b) # Creo la matriz b

producto_punto = np.dot(a_arrays,b_arrays)
print(f'El producto punto de a con b es: {producto_punto}')

El producto punto de a con b es: 44


In [17]:
import numpy as pd
# respuesta
# 4. ¿Qué pasa si multiplicas una matriz 2x3 por una 3x2?

# creamos una matriz 2x3 
matriz2X3 = np.array([[0,1,2],[3,4,5]])

# creamos una matriz 3x2
matriz3x2 = np.array([[0,1],[2,3],[3,4]])

print(f'Matriz 2x3\n{matriz2X3}')
print(f'\nMatriz 3x2\n{matriz3x2}')

multi = matriz2X3 * matriz3x2  # Se Produce un Error



Matriz 2x3
[[0 1 2]
 [3 4 5]]

Matriz 3x2
[[0 1]
 [2 3]
 [3 4]]


ValueError: operands could not be broadcast together with shapes (2,3) (3,2) 