# 📘 Clase 6: Álgebra lineal con NumPy
## 🎯 Objetivos

- Calcular determinantes, inversas y eigenvalores.

- Resolver sistemas de ecuaciones lineales.

- Entender la diferencia entre @, dot, y matmul.

## 📖 Teoría

El submódulo numpy.linalg permite resolver problemas de álgebra lineal de forma eficiente.

Operaciones principales:

- np.dot(A, B) o A @ B → producto matricial

- np.linalg.inv(A) → inversa

- np.linalg.det(A) → determinante

- np.linalg.eig(A) → eigenvalores y eigenvectores

- np.linalg.solve(A, b) → sistema lineal Ax=b

💻 Ejemplo

In [6]:
import numpy as np

A = np.array([[3, 1], [2, 4]])
b = np.array([7, 10])

print("Determinante:", np.linalg.det(A))
print("\nInversa:\n", np.linalg.inv(A))

x = np.linalg.solve(A, b)
print("\nSolución del sistema:", x)

valores, vectores = np.linalg.eig(A)
print("\nEigenvalores:", valores)
print("\nEigenvectores:\n", vectores)


Determinante: 10.000000000000002

Inversa:
 [[ 0.4 -0.1]
 [-0.2  0.3]]

Solución del sistema: [1.8 1.6]

Eigenvalores: [2. 5.]

Eigenvectores:
 [[-0.70710678 -0.4472136 ]
 [ 0.70710678 -0.89442719]]


## 🧩 Ejercicios

- Calcula la inversa y el determinante de una matriz 3x3.

- Resuelve el sistema lineal:

2x+3y=84x−y=2

- Obtén los eigenvalores de una matriz 2x2 y analiza su significado.

In [14]:
# Respuesta 
import numpy as np
np.random.seed(10)

# - Calcula la inversa y el determinante de una matriz 3x3.

# Creo la Matriz 3x3

Matriz3x3 = np.random.randint(2,12,[3,3])
print(f'La Matriz 3x3 es:\n {Matriz3x3}')

# Calculo la inversa
inversa = np.linalg.inv(Matriz3x3)
print(f'\nInversa de la Matriz:\n {inversa}')

# Calculo de determinante 
determinate = np.linalg.det(Matriz3x3)
print(f'\nEL Determinante de la Matriz es {determinate:.2f}')


La Matriz 3x3 es:
 [[11  6  2]
 [ 3 11  2]
 [ 3 10 11]]

Inversa de la Matriz:
 [[ 0.10710498 -0.04878049 -0.01060445]
 [-0.02863203  0.12195122 -0.01696713]
 [-0.00318134 -0.09756098  0.10922587]]

EL Determinante de la Matriz es 943.00
