# 📘 Clase 6: Álgebra lineal con NumPy
## 🎯 Objetivos

- Calcular determinantes, inversas y eigenvalores.

- Resolver sistemas de ecuaciones lineales.

- Entender la diferencia entre @, dot, y matmul.

## 📖 Teoría

El submódulo numpy.linalg permite resolver problemas de álgebra lineal de forma eficiente.

Operaciones principales:

- np.dot(A, B) o A @ B → producto matricial

- np.linalg.inv(A) → inversa

- np.linalg.det(A) → determinante

- np.linalg.eig(A) → eigenvalores y eigenvectores

- np.linalg.solve(A, b) → sistema lineal Ax=b

💻 Ejemplo

In [2]:
import numpy as np

A = np.array([[3, 1], [2, 4]])
b = np.array([7, 10])

print("Determinante de A:", np.linalg.det(A))
print("\nInversa:\n", np.linalg.inv(A))

x = np.linalg.solve(A, b)
print("\nSolución del sistema:", x)

valores, vectores = np.linalg.eig(A)
print("\nEigenvalores:", valores)
print("\nEigenvectores:\n", vectores)


Determinante de A: 10.000000000000002

Inversa:
 [[ 0.4 -0.1]
 [-0.2  0.3]]

Solución del sistema: [1.8 1.6]

Eigenvalores: [2. 5.]

Eigenvectores:
 [[-0.70710678 -0.4472136 ]
 [ 0.70710678 -0.89442719]]


## 🧩 Ejercicios

- Calcula la inversa y el determinante de una matriz 3x3.

- Resuelve el sistema lineal:

2x+3y=84
x−y=2

- Obtén los eigenvalores de una matriz 2x2 y analiza su significado.

In [14]:
# Respuesta 
import numpy as np
np.random.seed(10)

# - Calcula la inversa y el determinante de una matriz 3x3.

# Creo la Matriz 3x3

Matriz3x3 = np.random.randint(2,12,[3,3])
print(f'La Matriz 3x3 es:\n {Matriz3x3}')

# Calculo la inversa
inversa = np.linalg.inv(Matriz3x3)
print(f'\nInversa de la Matriz:\n {inversa}')

# Calculo de determinante 
determinate = np.linalg.det(Matriz3x3)
print(f'\nEL Determinante de la Matriz es {determinate:.2f}')


La Matriz 3x3 es:
 [[11  6  2]
 [ 3 11  2]
 [ 3 10 11]]

Inversa de la Matriz:
 [[ 0.10710498 -0.04878049 -0.01060445]
 [-0.02863203  0.12195122 -0.01696713]
 [-0.00318134 -0.09756098  0.10922587]]

EL Determinante de la Matriz es 943.00


In [7]:
import numpy as np
# respuesta 

# - Resuelve el sistema lineal:
#2x+3y=84
# x−y=2

# Paso 1 Convierto en matriz los coeficiente de cada variable

a = np.array([[2,3],[1,-1]]) # Matriz Coeficiente

# Paso 2 Convierto las igualdades en un vector matriz 
b = np.array([84,2])

# Paso # 3 Calculo la solucion a la Ecuacion 
solucion = np.linalg.solve(a,b)

x =  solucion[0]
y = solucion[1]

print(f"\nLa solución al sistema \n2x+3y=84\nx−y=2 es:")
print(f"\nx = {x:.2f}")
print(f"y = {y:.2f}")


La solución al sistema 
2x+3y=84
x−y=2 es:

x = 18.00
y = 16.00


In [8]:
import numpy as np
# Problema extra

# Utilizando NumPy, se pretende analizar la relación lineal definida por la función y = 3x + 5
# calcular el valor de y para cada uno de los siguientes valores de x = {-2, 0, 1, 5, 10}

# respuesta

x_valores = np.array([-2, 0, 1, 5, 10])

## Aplicación de la función usando Broadcasting

y_valores = 3*x_valores + 5 

print(f"Valores de X: {x_valores}")
print(f"\nValores de Y: {y_valores}")


Valores de X: [-2  0  1  5 10]

Valores de Y: [-1  5  8 20 35]


In [14]:
# Respuesta 
# - Obtén los eigenvalores de una matriz 2x2 y analiza su significado.
import numpy as np
np.random.seed(30)

matriz2x2 = np.random.randint(10,20,[2,2]) # Creacion de Matriz 2x2

print(f'Matriz de 2x2 \n{matriz2x2}')

# Calculando los eigenvalores 
valores, vectores = np.linalg.eig(matriz2x2)
print('\nEigenvalores:\n', valores)
print('\nEigenvectores:\n',vectores)

print('\nSignificado de los Eigenvalores:')
print('Cada eigenvalor indica la magnitud por la cual su eigenvector asociado es escalado (estirado o encogido) al aplicar la transformación de la matriz.')

print('\nAnálisis de los Eigenvalores: El primer vector se estira por un factor de 1.47, mientras que el segundo vector se estira por un factor de 30.52.')

Matriz de 2x2 
[[15 15]
 [14 17]]

Eigenvalores:
 [ 1.47416095 30.52583905]

Eigenvectores:
 [[-0.74265769 -0.69482306]
 [ 0.66967123 -0.71918073]]

Significado de los Eigenvalores:
Cada eigenvalor indica la magnitud por la cual su eigenvector asociado es escalado (estirado o encogido) al aplicar la transformación de la matriz.

Análisis de los Eigenvalores: El primer vector se estira por un factor de 1.47, mientras que el segundo vector se estira por un factor de 30.52.
