# 📘 Clase 1: Introducción y creación de arreglos
## 🎯 Objetivos

- Entender qué es NumPy y por qué se usa en ciencia de datos.

- Crear arreglos (ndarray) a partir de listas o funciones.

- Comprender la diferencia entre listas de Python y arrays de NumPy.

## 📖 Teoría rápida

NumPy (Numerical Python) es una librería que permite manejar grandes volúmenes de datos numéricos de forma eficiente.
Su estructura principal es el ndarray, que representa arreglos n-dimensionales.

Ventajas frente a las listas:

- Más rápido.

- Menor consumo de memoria.

- Permite operaciones vectorizadas (sin bucles explícitos).

💻 Ejemplo básico

In [ ]:
import numpy as np

# Crear arreglos
lista = [1, 2, 3, 4, 5]
arr = np.array(lista)

print("Lista normal:", lista)
print("Arreglo NumPy:", arr)

# Crear arreglos con funciones
zeros = np.zeros(5)                 # Creando matrix cero
ones = np.ones((2, 3))              # Creando Matrix de 1 
rango = np.arange(0, 10, 2)         
aleatorio = np.random.rand(3, 3)    #  creadno Matrix Aleatoria

print('\n---------------------------------------------')

print("Zeros:", zeros)
print("\nOnes:\n", ones)
print("\nRango:", rango)
print("\nAleatorio:\n", aleatorio)


Lista normal: [1, 2, 3, 4, 5]
Arreglo NumPy: [1 2 3 4 5]

---------------------------------------------
Zeros: [0. 0. 0. 0. 0.]

Ones:
 [[1. 1. 1.]
 [1. 1. 1.]]

Rango: [0 2 4 6 8]

Aleatorio:
 [[0.5505247  0.62899835 0.82566023]
 [0.45315664 0.59929057 0.55331844]
 [0.01183392 0.82138776 0.38757419]]


## 🧩 Ejercicios

1. Crea un arreglo NumPy del 1 al 20.

2. Genera un arreglo 3x3 lleno de números aleatorios entre 0 y 1.

3. Crea un arreglo de ceros de tamaño 5 y reemplaza el tercer elemento por 10.

4. Usa np.linspace(0, 1, 6) y explica qué hace.

In [ ]:
import numpy as pd
# Respuestas
# 1. Crea un arreglo NumPy del 1 al 20.

import numpy as np   # importo biblioteca

arreglo =np.arange(1,21)      # creando arreglo
print(arreglo)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]


In [ ]:
import numpy as pd
# Respuesta
#2. Genera un arreglo 3x3 lleno de números aleatorios entre 0 y 1.

aleatorio =np.random.rand(3,3) # Creando aleatorios
print(aleatorio)

[[0.96868956 0.08054232 0.08207825]
 [0.41362264 0.9894949  0.84662216]
 [0.42493384 0.82231149 0.48277502]]


In [ ]:
import numpy as np
# Respuesta
# 3. Crea un arreglo de ceros de tamaño 5 y reemplaza el tercer elemento por 10.

arreglos = np.zeros(5)  # creando y mostrado arreglo de cero
print(f'Arreglo origital: {arreglos}')

arreglos[2]=10 # modificando el tercer elemento
print(f'Arreglo modificado: {arreglos}')



Arreglo origital: [0. 0. 0. 0. 0.]
Arreglo modificado: [ 0.  0. 10.  0.  0.]


In [27]:
import numpy as pd
# Respuesta
# 4. Usa np.linspace(0, 1, 6) y explica qué hace.

linspa = np.linspace(0, 1, 6)
print(linspa)

print('Se crea un arreglo con 6 números flotantes igualmente espaciados, comenzando en 0 y terminando en 1 (ambos inclusivos).')

[0.  0.2 0.4 0.6 0.8 1. ]
Se crea un arreglo con 6 números flotantes igualmente espaciados, comenzando en 0 y terminando en 1 (ambos inclusivos).
