# 📘 Clase 3: Indexación, slicing y manipulación
## 🎯 Objetivos

- Seleccionar y modificar elementos específicos.

- Aplicar slicing (subarreglos).

- Cambiar forma (reshape) y concatenar.

💻 Ejemplo

In [ ]:
import numpy as np

arr = np.arange(10)  # matriz de una fila del diez elementos 
print("Original:", arr)

# Indexación y slicing
print(f'\n Indexacion y slicing: {arr[2:6]}')
arr[3:7] = 100
print("\nModificado:\n", arr)

# Reestructurar
mat = np.arange(12).reshape(3, 4)  # arange(n elementos).reshape(fila,columna)
print("\nMatriz 3x4:\n", mat)

# Concatenar
mat2 = np.ones((3, 4))
resultado = np.concatenate([mat, mat2], axis=0)   # Combinacion de matriz 
print("Concatenado:\n", resultado)


Original: [0 1 2 3 4 5 6 7 8 9]

 Indexacion y slicing: [2 3 4 5]

Modificado:
 [  0   1   2 100 100 100 100   7   8   9]

Matriz 3x4:
 [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
Concatenado:
 [[ 0.  1.  2.  3.]
 [ 4.  5.  6.  7.]
 [ 8.  9. 10. 11.]
 [ 1.  1.  1.  1.]
 [ 1.  1.  1.  1.]
 [ 1.  1.  1.  1.]]


# 🧩 Ejercicios

1. Crea un arreglo del 0 al 9 y reemplaza los elementos del 3 al 6 por 99.

2. Genera una matriz 4x3 con números del 1 al 12 y toma solo la primera y última columna.

3. Une dos matrices 2x2 por filas y luego por columnas.

In [9]:
# Respuesta 
import numpy as np
#1. Crea un arreglo del 0 al 9 y reemplaza los elementos del 3 al 6 por 99.

arreglo_0_99 = np.arange(10)
print(f'Matriz original: {arreglo_0_99}')

#modifico los elementos del 3 al 6 
arreglo_0_99[3:7] = 99
print(f'Matriz Modificada {arreglo_0_99}')

Matriz original: [0 1 2 3 4 5 6 7 8 9]
Matriz Modificada [ 0  1  2 99 99 99 99  7  8  9]


In [36]:
# Respuesta 
import numpy as np
# 2. Genera una matriz 4x3 con números del 1 al 12 y toma solo la primera y última columna.

matriz4x3= np.arange(1,13).reshape(4,3)
print(f'Matriz 4X3\n{matriz4x3}')

# Seleccion de la primera Fila
fila_uno =matriz4x3[0]
print(f'\nLa Primera fila de la matriz 4x3 es\n{fila_uno}')

# Seleccion de la ultima columna
ultima_columna = matriz4x3[:,2:]              #matriz[fila,columna]  # Matriz[:,columnas:]

print(f'\nLa ultima fila de la matriz 4x3 es\n {ultima_columna}')


Matriz 4X3
[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]

La Primera fila de la matriz 4x3 es
[1 2 3]

La ultima fila de la matriz 4x3 es
 [[ 3]
 [ 6]
 [ 9]
 [12]]


In [35]:
# respuesta 
import numpy as np
# 3. Une dos matrices 2x2 por filas y luego por columnas.

# Creo Matriz 1 y 2
matriz_1 = np.array([[10,5],[2,4]])
matriz_2 = np.array([[1,2],[5,6]])

# uno matriz por columnas
union_columna= np.concatenate([matriz_1,matriz_2],axis=1)  # axis = 0 Se unen por fila
                                                   # axis = 1 Se unen por columnas
                                                   # axis = None se cre una sola fila de elementos

print(f'Union por Columna\n {union_columna}')

# uno matriz por fila
union_fila = np.concatenate([matriz_1,matriz_2],axis=0)

print(f'\nUnion por fila\n {union_fila}')


Union por Columna
 [[10  5  1  2]
 [ 2  4  5  6]]

Union por fila
 [[10  5]
 [ 2  4]
 [ 1  2]
 [ 5  6]]
