# 📘 Clase 9: Vistas vs copias y optimización de memoria
## 🎯 Objetivos

- Diferenciar entre vistas (view) y copias (copy).

- Comprender cómo NumPy maneja la memoria.

- Aplicar slicing sin duplicar datos.

## 📖 Teoría

NumPy trabaja con vistas por defecto: muchas operaciones no duplican datos, solo cambian la forma de ver el mismo bloque de memoria.

In [1]:
import numpy as np

arr = np.arange(10)
view = arr[3:7]
copy = arr[3:7].copy()

view[:] = 99
print(arr)  # Cambia el original
print(copy)  # Independiente


[ 0  1  2 99 99 99 99  7  8  9]
[3 4 5 6]


## 🧩 Ejercicios

1. Muestra un ejemplo donde modificar una vista afecta el arreglo original.

2. Crea una copia explícita y demuestra que es independiente.

3. ¿Por qué las vistas son más rápidas?

In [ ]:
# Respuesta 
# 1. Muestra un ejemplo donde modificar una vista afecta el arreglo original.

arreglo = np.arange(15)# Creando el arreglo 
print(arreglo) # visualizando el arreglo original

#seleccionando una porcion del arreglo 
vista = arreglo[2:5]
print('\n',vista) # visualizando el arreglo seleccionado

# copiando arreglo vista desde el orginal
copia = arreglo[2:5].copy()
# modificando el arrego vista 

vista[:]=10

print(f'\nVisualizando arreglo original modificado {arreglo}')



[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]

 [2 3 4]

Visualizando arreglo original [ 0  1 10 10 10  5  6  7  8  9 10 11 12 13 14]


In [15]:
# Respuesta 
# 2. Crea una copia explícita y demuestra que es independiente.

arreglo_original = np.arange(20) # creando arreglo original 

copia = arreglo_original.copy() # Creando Arreglo copia

# modifico arreglo copia para demostrar independencia 
copia[18:20] = 100

print(f'\nArreglo original{arreglo_original}\n\nArreglo copia\n{copia}')



Arreglo original[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]

Arreglo copia
[  0   1   2   3   4   5   6   7   8   9  10  11  12  13  14  15  16  17
 100 100]


In [16]:
# Respuesta 
# 3. ¿Por qué las vistas son más rápidas?
print('--- ¿POR QUÉ LAS VISTAS SON MÁS RÁPIDAS? ---')
print('La vista es más rápida porque NUNCA COPIA los datos. 🚀')
print('1. Referencia a Memoria: Una vista es simplemente una "ventana" o referencia a una porción específica del arreglo original en la memoria.')
print('2. Eficiencia: Al no copiar, NumPy evita el gasto de tiempo y recursos (memoria RAM) que implica mover grandes cantidades de datos.')
print('3. Consecuencia: Cualquier modificación que hagas en la vista, se aplica directamente al arreglo original, porque ambos comparten la misma ubicación de datos.')
print('--- LAS VISTAS SON RÁPIDAS PERO NO INDEPENDIENTES ---')

--- ¿POR QUÉ LAS VISTAS SON MÁS RÁPIDAS? ---
La vista es más rápida porque NUNCA COPIA los datos. 🚀
1. Referencia a Memoria: Una vista es simplemente una "ventana" o referencia a una porción específica del arreglo original en la memoria.
2. Eficiencia: Al no copiar, NumPy evita el gasto de tiempo y recursos (memoria RAM) que implica mover grandes cantidades de datos.
3. Consecuencia: Cualquier modificación que hagas en la vista, se aplica directamente al arreglo original, porque ambos comparten la misma ubicación de datos.
--- LAS VISTAS SON RÁPIDAS PERO NO INDEPENDIENTES ---
