# 📘 Clase 8: Broadcasting avanzado
## 🎯 Objetivos

- Entender las reglas de broadcasting.

- Aplicarlas en operaciones entre arreglos de distinta forma.

- Evitar errores de incompatibilidad.

📖 Teoría

El broadcasting permite que NumPy realice operaciones entre arreglos de tamaños distintos, extendiendo automáticamente dimensiones cuando es posible.

Reglas:

1. Se comparan las dimensiones desde el final hacia el inicio.

2. Si son iguales o alguna es 1 → compatibles.

3. Si son diferentes y ninguna es 1 → error.

💻 Ejemplo

In [1]:
import numpy as np

mat = np.array([[1, 2, 3],
                [4, 5, 6]])

columna = np.array([[10],
                    [20]])

print(mat + columna)  # Broadcasting vertical


[[11 12 13]
 [24 25 26]]


## 🧩 Ejercicios

1. Explica por qué np.ones((3,1)) + np.arange(3) funciona.

2. Crea un tensor 2x3x4 y súmale un vector de tamaño 4.

3. Diseña un ejemplo donde falle el broadcasting y arréglalo.

In [2]:
import numpy as np

# Respuesta
# 1. Explica por qué np.ones((3,1)) + np.arange(3) funciona.


ab = np.ones((3,1)) + np.arange(3)

print(ab)
print('\nEsta operación funciona por el "Broadcasting" de NumPy.')
print('El arreglo (3,1) y el arreglo (3,) son compatibles porque NumPy estira virtualmente el vector fila np.arange(3) para que se sume a cada fila de la matriz columna np.ones((3,1)), resultando en una matriz (3,3).')


[[1. 2. 3.]
 [1. 2. 3.]
 [1. 2. 3.]]

Esta operación funciona por el "Broadcasting" de NumPy.
El arreglo (3,1) y el arreglo (3,) son compatibles porque NumPy estira virtualmente el vector fila np.arange(3) para que se sume a cada fila de la matriz columna np.ones((3,1)), resultando en una matriz (3,3).


In [3]:
# Respuesta
# 2. Crea un tensor 2x3x4 y súmale un vector de tamaño 4.
import numpy as np
np.random.seed(15)

tensor2x3x4 = np.random.randint(1,10,[2,3,4]) # Creacion del tensor
print(f'Tensor 2x3x4 (forma: {tensor2x3x4.shape}):\n{tensor2x3x4}')

vector_4= np.arange(1,5)
print(f"\nVector de tamaño 4 (Forma: {vector_4.shape}):\n{vector_4}")

# Sumo el Vector mas el Tensor

Sumo = tensor2x3x4 + vector_4

print(f"\nResultado de la suma (Forma: {Sumo.shape}):")
print(Sumo)

Tensor 2x3x4 (forma: (2, 3, 4)):
[[[9 6 6 8]
  [1 8 6 7]
  [2 8 1 5]]

 [[8 6 4 7]
  [9 3 2 2]
  [1 6 3 3]]]

Vector de tamaño 4 (Forma: (4,)):
[1 2 3 4]

Resultado de la suma (Forma: (2, 3, 4)):
[[[10  8  9 12]
  [ 2 10  9 11]
  [ 3 10  4  9]]

 [[ 9  8  7 11]
  [10  5  5  6]
  [ 2  8  6  7]]]


In [5]:
# Respuesta
# 3. Diseña un ejemplo donde falle el broadcasting y arréglalo.

import numpy as np

# Arreglo 1: Matriz Columna (3 filas, 1 columna)
A = np.array([[1], 
              [2], 
              [3]])  # Forma (3, 1)

# Arreglo 2: Vector Fila de 2 elementos
B = np.array([10, 20])  # Forma (2,)

print(f"Forma de A: {A.shape}")
print(f"Forma de B: {B.shape}")

# Intento de suma que FALLARÁ
try:
    suma = A + B
    print(suma)
except ValueError as e:
    print("\n--- ERROR DE BROADCASTING ---")
    print(f"La suma falla porque: {e}")
    print("\n[EXPLICACIÓN DEL FALLO]:")
    print("NumPy intenta comparar las formas de derecha a izquierda:")
    print("1. El tamaño 1 de A no coincide con el tamaño 2 de B.")
    print("2. Las dimensiones deben ser iguales o una debe ser 1 (y aquí son 1 y 2, y luego 3 y nada).")
   print("3. Como la dimensión (1) y (2) no coinciden y ninguna es 1 o la misma, el Broadcasting falla.")

IndentationError: unindent does not match any outer indentation level (<string>, line 28)

In [ ]:
import numpy as np

# Arreglo 1: Matriz Columna de 2x1 (CORREGIDA)
A_corregido = np.array([[10], 
                        [20]])  # Forma (2, 1)

# Arreglo 2: Vector Fila de 2 elementos (B)
B = np.array([1, 2])  # Forma (2,)

print(f"\n--- SOLUCIÓN (A cambió a 2x1) ---")
print(f"Forma de A_corregido: {A_corregido.shape}")
print(f"Forma de B: {B.shape}")

# ¡Ahora la suma funciona!
suma_arreglada = A_corregido + B
print("\nResultado de la suma arreglada (Broadcasting exitoso):")
print(suma_arreglada)


--- SOLUCIÓN (A cambió a 2x1) ---
Forma de A_corregido: (2, 1)
Forma de B: (2,)

Resultado de la suma arreglada (Broadcasting exitoso):
[[11 12]
 [21 22]]
