# 📘 Clase 5: Máscaras booleanas y filtrado condicional
## 🎯 Objetivos

- Crear máscaras lógicas para seleccionar subconjuntos de datos.

- Aplicar condiciones sobre arreglos.

- Usar operadores lógicos (&, |, ~) en arreglos.

## 📖 Teoría

Una máscara booleana es un arreglo de valores True o False del mismo tamaño que otro arreglo.
Se usa para filtrar elementos según condiciones.

Por ejemplo:

In [1]:
import numpy as np

arr = np.arange(10)  
mascara = arr > 5    # Selecciona los numero mayores que cinco 
print("Máscara:", mascara)
print("Elementos mayores a 5:", arr[mascara])


Máscara: [False False False False False False  True  True  True  True]
Elementos mayores a 5: [6 7 8 9]


### Operadores lógicos en NumPy:

- & → AND lógico

- | → OR lógico

- ~ → NOT lógico

## 🧩 Ejercicios

- Genera un arreglo con números del 0 al 20 y selecciona los múltiplos de 3.

- Crea un arreglo de 15 valores aleatorios entre 1 y 100, filtra los mayores que 50 y menores que 80.

-  Calcula el promedio solo de los valores que cumplan cierta condición.

In [ ]:
# Respuesta 
import numpy as np
# - Genera un arreglo con números del 0 al 20 y selecciona los múltiplos de 3.

arreglo = np.arange(0,21)
print(f'Datos Numericos:\n{arreglo}')

# seleccion de valores 
mayores_3 = arreglo % 3 == 0

print(f'\nLos numero de los datos numericos divisible entre 3 son:\n{arreglo[mayores_3]}')

Datos Numericos:
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]

Los numero de los datos numericos divisible entre 3 son:
[ 0  3  6  9 12 15 18]


In [13]:
# Respuesta 
import numpy as np
np.random.seed(40)
# Crea un arreglo de 15 valores aleatorios entre 1 y 100, filtra los mayores que 50 y menores que 80.

valores_aleatorio = np.random.randint(1,100,15) # creando los valores aleatorio
print(f'La Lista de valores es:\n{valores_aleatorio}') 

# Desarrollo Filtro
filtrado = (valores_aleatorio > 50) & (valores_aleatorio < 80)

print(f'\nLos valores seleccionado son:\n{valores_aleatorio[filtrado]}')



La Lista de valores es:
[71 92  8 38 57 51 66 13 72 20 32 75 56 84 60]

Los valores seleccionado son:
[71 57 51 66 72 75 56 60]


In [19]:
# Respuesta 
# -  Calcula el promedio solo de los valores que cumplan cierta condición.
import numpy as np
np.random.seed(50)

valores = np.random.randint(1,50,10)
print(f'Valores obtenido:{valores}')

# Selecciono los valores mayores a 36 y menores a 40
filtrado = (valores > 36) & (valores < 40)

print(f'\nEl promedio de los valores filtrados son:\n{np.mean(valores[filtrado])}')

Valores obtenido:[49 33 12 46 34 31  5  7 38  7]

El promedio de los valores filtrados son:
38.0
