# 📘 Clase 4: Estadística básica y broadcasting
## 🎯 Objetivos

- Calcular estadísticas simples con NumPy.

- Comprender y aplicar broadcasting para operaciones entre arreglos de distinta forma

💻 Ejemplo

In [3]:
import numpy as np

datos = np.random.randint(1, 100, 10) # radint(elige diez numero al azar 1 al 100)
print("Datos:", datos)

print("\nMedia:", np.mean(datos))
print("\nMediana:", np.median(datos))
print("\nDesviación estándar:", np.std(datos))

# Broadcasting
mat = np.array([[1, 2, 3],
                [4, 5, 6]])

vector = np.array([10, 20, 30])

print("\nResultado broadcasting:\n", mat + vector)


Datos: [16 60 60 20  7 84 74 26 60 81]

Media: 48.8

Mediana: 60.0

Desviación estándar: 27.312268305653415

Resultado broadcasting:
 [[11 22 33]
 [14 25 36]]


## 🧩 Ejercicios

1. Genera 10 números aleatorios entre 1 y 50 y calcula su media, mediana y desviación estándar.

2. Crea una matriz 2x3 y súmale un vector de tamaño 3.

3. Explica con tus palabras cómo funciona el broadcasting.

In [17]:
# Respuesta 
import numpy as np
# 1. Genera 10 números aleatorios entre 1 y 50 y calcula su media, mediana y desviación estándar.

datos_1 =np.random.randint(1,50,10)
print(f'Datos: {datos_1}')

#Calculos de la media,mediana y desviacion estandar

media_datos = np.mean(datos_1)  # media
print(f'\nMedia de los Datos {media_datos}')

mediana_datos = np.median(datos_1)    # mediana
print(f'\nMediana de los Datos {mediana_datos}')

desviacion_estandar = np.std(datos_1)
print(f'\nDesviacion Estandar {desviacion_estandar:.2f}')

Datos: [ 5 17  6 33  4 48 43 15 31 42]

Media de los Datos 24.4

Mediana de los Datos 24.0

Desviacion Estandar 16.14


In [ ]:
import numpy as np
# Respuesta 
# 2. Crea una matriz 2x3 y súmale un vector de tamaño 3.

matriz_2x3 =np.random.randint(1,25,[2,3]) # creo una matriz aleatoria
print(f'Matriz: \n{matriz_2x3}')

vector_3=np.arange(1,4) # creo vector
print(f'\nVector: \n{vector_3}')

# sumo la matriz mas el vector con Broadcasting
Suma = matriz_2x3 + vector_3

print(f'\nResultado del Broadcasting:\n{matriz_2x3 + vector_3}')


Matriz: 
[[11  7  2]
 [ 6 13 17]]

Vector: 
[1 2 3]

Resultado del Broadcasting:
[[12  9  5]
 [ 7 15 20]]


In [29]:
#Respuesta
# 3. Explica con tus palabras cómo funciona el broadcasting.

print('\nExplicación Broadcasting:')
print('NumPy aplica el "Broadcasting": el vector de tamaño 3 se copia virtualmente y se suma a CADA FILA de la matriz 2x3, sin consumir memoria adicional.')


Explicación Broadcasting:
NumPy aplica el "Broadcasting": el vector de tamaño 3 se copia virtualmente y se suma a CADA FILA de la matriz 2x3, sin consumir memoria adicional.


## 💼 Ejercicios de la vida real

1. Simulación de calificaciones:

- Genera un arreglo de 30 calificaciones (valores entre 0 y 100).

- Calcula media, máximo, mínimo y cuántos aprobaron (≥ 60).

2. Análisis de temperaturas:

- Crea un arreglo con las temperaturas diarias (7 días, 4 semanas → matriz 4x7).

- Calcula el promedio semanal y el día más caluroso.

In [46]:
# Respuesta 
# 1. Simulación de calificaciones:
# - Genera un arreglo de 30 calificaciones (valores entre 0 y 100).
import numpy as np
np.random.seed(10)

notas = np.random.randint(0,100,30)
print(f'Nota de los estudiantes:\n{notas}')

# - Calcula media, máximo, mínimo y cuántos aprobaron (≥ 60).

# Calculo la media 
media_notas = np.mean(notas)
print(f'\nLa media de las notas de los estudiantes es: {media_notas:.2f} puntos')

# Calculo la Maxima Nota
maximo_notas = np.max(notas)
print(f'\nLa mayor nota es {maximo_notas} puntos')

# Calculo la minima nota
minimo_notas = np.min(notas)
print(f'\nLa minima nota es {minimo_notas} puntos ')

# calculamos cuanto aprobaron
notas_mayor_60 = notas>=60

aprobaron = len(notas[notas_mayor_60])
print(f'\nLa cantidad de estudiantes que abrobaron es {aprobaron} estudiantes')

Nota de los estudiantes:
[ 9 15 64 28 89 93 29  8 73  0 40 36 16 11 54 88 62 33 72 78 49 51 54 77
 69 13 25 13 92 86]

La media de las notas de los estudiantes es: 47.57 puntos

La mayor nota es 93 puntos

La minima nota es 0 puntos 

La cantidad de estudiantes que abrobaron es 12 estudiantes


In [71]:
# Respuesta
import numpy as np
# 2. Análisis de temperaturas:
# - Crea un arreglo con las temperaturas diarias (7 días, 4 semanas → matriz 4x7).
np.random.seed(32)

temperatura = np.random.randint(-100,100,[4,7]) #matriz de temperatura
print(f'Tabla de Temperatura:\n {temperatura}') 

# - Calcula el promedio semanal 

temperatura_promedio_semanal = np.mean(temperatura,axis=1) # promedio semanal
# Extraemos los valores de la temperatura de la lista
for i, promedio in enumerate(temperatura_promedio_semanal):
    print(f'\nSemana {i+1}: {promedio:.2f} °C')


# Dia mas Caluroso

maxima_temperatura = np.max(temperatura)

# Usamos argmax para encontrar la posición (índice plano) del máximo
posicion_max = np.argmax(temperatura)

# Usamos unravel_index para convertir ese índice plano en (fila, columna)
posicion_2d = np.unravel_index(posicion_max, temperatura.shape)

semana = posicion_2d[0] + 1
dia_de_semana = posicion_2d[1] + 1

print(f'\nLa Temperatura más alta es: {maxima_temperatura} °C')
print(f'Ocurrió en la Semana {semana}, Día {dia_de_semana} (Índice 2D: {posicion_2d})')


Tabla de Temperatura:
 [[-57  33 -46  24  90 -12  47]
 [-29 -11 -97 -91 -96  39 -97]
 [-35  62 -65 -76 -58 -18  38]
 [ 78   0   0  85  97  66 -23]]

Semana 1: 11.29 °C

Semana 2: -54.57 °C

Semana 3: -21.71 °C

Semana 4: 43.29 °C

La Temperatura más alta es: 97 °C
Ocurrió en la Semana 4, Día 5 (Índice 2D: (np.int64(3), np.int64(4)))
